"""initial schema

Revision ID: 7b0f0b6ea8ea
Revises:
Create Date: 2026-08-05 04:15:33.725661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b0f0b6ea8ea"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("parent_category_id", sa.String(length=36), nullable=True),
        sa.Column("category_key", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_category_id"], ["categories.id"], name=op.f("fk_categories_parent_category_id_categories")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    op.create_index(op.f("ix_categories_category_key"), "categories", ["category_key"], unique=True)
    op.create_index(op.f("ix_categories_parent_category_id"), "categories", ["parent_category_id"], unique=False)
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=True)
    op.create_table(
        "code_sequences",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("prefix", sa.String(length=10), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("year", "prefix", name=op.f("pk_code_sequences")),
    )
    op.create_table(
        "freelancer_levels",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("level_key", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("rank_order", sa.Integer(), nullable=False),
        sa.Column("access_type", sa.String(length=20), nullable=False),
        sa.Column("min_completed_projects", sa.Integer(), nullable=False),
        sa.Column("min_rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("max_active_applications", sa.Integer(), nullable=True),
        sa.Column("can_apply_public_projects", sa.Boolean(), nullable=False),
        sa.Column("can_apply_private_projects", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_freelancer_levels")),
    )
    op.create_index(op.f("ix_freelancer_levels_level_key"), "freelancer_levels", ["level_key"], unique=True)
    op.create_table(
        "permissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("permission_key", sa.String(length=120), nullable=False),
        sa.Column("module", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
    )
    op.create_index(op.f("ix_permissions_permission_key"), "permissions", ["permission_key"], unique=True)
    op.create_table(
        "roles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("role_key", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
    )
    op.create_index(op.f("ix_roles_role_key"), "roles", ["role_key"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=120), nullable=False),
        sa.Column("last_name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "category_supervisors",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("category_id", sa.String(length=36), nullable=False),
        sa.Column("supervisor_user_id", sa.String(length=36), nullable=False),
        sa.Column("assigned_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_category_supervisors_category_id_categories")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category_supervisors")),
    )
    op.create_index(op.f("ix_category_supervisors_category_id"), "category_supervisors", ["category_id"], unique=False)
    op.create_index(
        op.f("ix_category_supervisors_supervisor_user_id"), "category_supervisors", ["supervisor_user_id"], unique=False
    )
    op.create_table(
        "form_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("category_id", sa.String(length=36), nullable=False),
        sa.Column("template_key", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("published_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_form_templates_category_id_categories")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_templates")),
    )
    op.create_index(op.f("ix_form_templates_category_id"), "form_templates", ["category_id"], unique=False)
    op.create_index(op.f("ix_form_templates_template_key"), "form_templates", ["template_key"], unique=True)
    op.create_table(
        "freelancer_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("current_level_id", sa.String(length=36), nullable=True),
        sa.Column("approval_status", sa.String(length=20), nullable=False),
        sa.Column("approved_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_note", sa.String(length=500), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("headline", sa.String(length=200), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("country_code", sa.String(length=10), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("hourly_rate_min", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("hourly_rate_max", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["current_level_id"],
            ["freelancer_levels.id"],
            name=op.f("fk_freelancer_profiles_current_level_id_freelancer_levels"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_freelancer_profiles_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_freelancer_profiles")),
    )
    op.create_index(
        op.f("ix_freelancer_profiles_current_level_id"), "freelancer_profiles", ["current_level_id"], unique=False
    )
    op.create_index(op.f("ix_freelancer_profiles_user_id"), "freelancer_profiles", ["user_id"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_code", sa.String(length=50), nullable=False),
        sa.Column("customer_user_id", sa.String(length=36), nullable=False),
        sa.Column("category_id", sa.String(length=36), nullable=False),
        sa.Column("form_template_id", sa.String(length=36), nullable=False),
        sa.Column("assigned_supervisor_user_id", sa.String(length=36), nullable=True),
        sa.Column("selected_application_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("budget_type", sa.String(length=20), nullable=False),
        sa.Column("fixed_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("min_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("max_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency_code", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("application_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_supervisor_user_id"], ["users.id"], name=op.f("fk_projects_assigned_supervisor_user_id_users")
        ),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], name=op.f("fk_projects_category_id_categories")),
        sa.ForeignKeyConstraint(["customer_user_id"], ["users.id"], name=op.f("fk_projects_customer_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(
        op.f("ix_projects_assigned_supervisor_user_id"), "projects", ["assigned_supervisor_user_id"], unique=False
    )
    op.create_index(op.f("ix_projects_category_id"), "projects", ["category_id"], unique=False)
    op.create_index(op.f("ix_projects_customer_user_id"), "projects", ["customer_user_id"], unique=False)
    op.create_index(op.f("ix_projects_project_code"), "projects", ["project_code"], unique=True)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("jti", sa.String(length=120), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_name", sa.String(length=120), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_token_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    op.create_index(op.f("ix_refresh_tokens_jti"), "refresh_tokens", ["jti"], unique=True)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("permission_id", sa.String(length=36), nullable=False),
        sa.Column("granted_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], name=op.f("fk_role_permissions_permission_id_permissions")
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name=op.f("fk_role_permissions_role_id_roles")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_permissions")),
        sa.UniqueConstraint("role_id", "permission_id", name="uq_role_permissions_role_id_permission_id"),
    )
    op.create_index(op.f("ix_role_permissions_permission_id"), "role_permissions", ["permission_id"], unique=False)
    op.create_index(op.f("ix_role_permissions_role_id"), "role_permissions", ["role_id"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("assigned_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_roles")),
    )
    op.create_index(op.f("ix_user_roles_role_id"), "user_roles", ["role_id"], unique=False)
    op.create_index(op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False)
    op.create_table(
        "form_fields",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("form_template_id", sa.String(length=36), nullable=False),
        sa.Column("field_key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("field_type", sa.String(length=20), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("is_repeatable", sa.Boolean(), nullable=False),
        sa.Column("is_unique", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("validation_rules", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_template_id"], ["form_templates.id"], name=op.f("fk_form_fields_form_template_id_form_templates")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_fields")),
    )
    op.create_index(op.f("ix_form_fields_form_template_id"), "form_fields", ["form_template_id"], unique=False)
    op.create_table(
        "freelancer_level_history",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("freelancer_profile_id", sa.String(length=36), nullable=False),
        sa.Column("old_level_id", sa.String(length=36), nullable=True),
        sa.Column("new_level_id", sa.String(length=36), nullable=False),
        sa.Column("assigned_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["freelancer_profile_id"],
            ["freelancer_profiles.id"],
            name=op.f("fk_freelancer_level_history_freelancer_profile_id_freelancer_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["new_level_id"],
            ["freelancer_levels.id"],
            name=op.f("fk_freelancer_level_history_new_level_id_freelancer_levels"),
        ),
        sa.ForeignKeyConstraint(
            ["old_level_id"],
            ["freelancer_levels.id"],
            name=op.f("fk_freelancer_level_history_old_level_id_freelancer_levels"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_freelancer_level_history")),
    )
    op.create_index(
        op.f("ix_freelancer_level_history_freelancer_profile_id"),
        "freelancer_level_history",
        ["freelancer_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_freelancer_level_history_new_level_id"), "freelancer_level_history", ["new_level_id"], unique=False
    )
    op.create_table(
        "portfolio_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("freelancer_profile_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("external_url", sa.String(length=500), nullable=True),
        sa.Column("file_asset_id", sa.String(length=36), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["freelancer_profile_id"],
            ["freelancer_profiles.id"],
            name=op.f("fk_portfolio_items_freelancer_profile_id_freelancer_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_items")),
    )
    op.create_index(
        op.f("ix_portfolio_items_freelancer_profile_id"), "portfolio_items", ["freelancer_profile_id"], unique=False
    )
    op.create_table(
        "project_applications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("freelancer_profile_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        sa.Column("proposed_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("proposed_days", sa.Integer(), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.String(length=500), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["freelancer_profile_id"],
            ["freelancer_profiles.id"],
            name=op.f("fk_project_applications_freelancer_profile_id_freelancer_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_project_applications_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_applications")),
    )
    op.create_index(
        op.f("ix_project_applications_freelancer_profile_id"),
        "project_applications",
        ["freelancer_profile_id"],
        unique=False,
    )
    op.create_index(op.f("ix_project_applications_project_id"), "project_applications", ["project_id"], unique=False)
    op.create_table(
        "project_deliveries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("submitted_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("delivery_note", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer_user_id", sa.String(length=36), nullable=True),
        sa.Column("superseded_by_delivery_id", sa.String(length=36), nullable=True),
        sa.Column("file_asset_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_project_deliveries_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_delivery_id"],
            ["project_deliveries.id"],
            name=op.f("fk_project_deliveries_superseded_by_delivery_id_project_deliveries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_deliveries")),
    )
    op.create_index(op.f("ix_project_deliveries_project_id"), "project_deliveries", ["project_id"], unique=False)
    op.create_table(
        "project_status_history",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("from_status", sa.String(length=30), nullable=True),
        sa.Column("to_status", sa.String(length=30), nullable=False),
        sa.Column("changed_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_project_status_history_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_status_history")),
    )
    op.create_index(
        op.f("ix_project_status_history_project_id"), "project_status_history", ["project_id"], unique=False
    )
    op.create_table(
        "resumes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("freelancer_profile_id", sa.String(length=36), nullable=False),
        sa.Column("file_asset_id", sa.String(length=36), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["freelancer_profile_id"],
            ["freelancer_profiles.id"],
            name=op.f("fk_resumes_freelancer_profile_id_freelancer_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resumes")),
    )
    op.create_index(op.f("ix_resumes_freelancer_profile_id"), "resumes", ["freelancer_profile_id"], unique=False)
    op.create_table(
        "tickets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ticket_code", sa.String(length=50), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("assigned_to_user_id", sa.String(length=36), nullable=True),
        sa.Column("related_project_id", sa.String(length=36), nullable=True),
        sa.Column("related_category_id", sa.String(length=36), nullable=True),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("closed_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["related_category_id"], ["categories.id"], name=op.f("fk_tickets_related_category_id_categories")
        ),
        sa.ForeignKeyConstraint(
            ["related_project_id"], ["projects.id"], name=op.f("fk_tickets_related_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
    )
    op.create_index(op.f("ix_tickets_assigned_to_user_id"), "tickets", ["assigned_to_user_id"], unique=False)
    op.create_index(op.f("ix_tickets_created_by_user_id"), "tickets", ["created_by_user_id"], unique=False)
    op.create_index(op.f("ix_tickets_related_category_id"), "tickets", ["related_category_id"], unique=False)
    op.create_index(op.f("ix_tickets_related_project_id"), "tickets", ["related_project_id"], unique=False)
    op.create_index(op.f("ix_tickets_ticket_code"), "tickets", ["ticket_code"], unique=True)
    op.create_table(
        "customer_reviews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("project_delivery_id", sa.String(length=36), nullable=False),
        sa.Column("customer_user_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_delivery_id"],
            ["project_deliveries.id"],
            name=op.f("fk_customer_reviews_project_delivery_id_project_deliveries"),
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], name=op.f("fk_customer_reviews_project_id_projects")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_reviews")),
    )
    op.create_index(
        op.f("ix_customer_reviews_customer_user_id"), "customer_reviews", ["customer_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_customer_reviews_project_delivery_id"), "customer_reviews", ["project_delivery_id"], unique=False
    )
    op.create_index(op.f("ix_customer_reviews_project_id"), "customer_reviews", ["project_id"], unique=False)
    op.create_table(
        "form_field_options",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("form_field_id", sa.String(length=36), nullable=False),
        sa.Column("option_key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_field_id"], ["form_fields.id"], name=op.f("fk_form_field_options_form_field_id_form_fields")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_field_options")),
    )
    op.create_index(op.f("ix_form_field_options_form_field_id"), "form_field_options", ["form_field_id"], unique=False)
    op.create_table(
        "project_revision_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("project_delivery_id", sa.String(length=36), nullable=True),
        sa.Column("requested_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("requested_to_user_id", sa.String(length=36), nullable=True),
        sa.Column("round_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("resolved_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_delivery_id"],
            ["project_deliveries.id"],
            name=op.f("fk_project_revision_requests_project_delivery_id_project_deliveries"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_project_revision_requests_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_revision_requests")),
    )
    op.create_index(
        op.f("ix_project_revision_requests_project_delivery_id"),
        "project_revision_requests",
        ["project_delivery_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_revision_requests_project_id"), "project_revision_requests", ["project_id"], unique=False
    )
    op.create_table(
        "supervisor_reviews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_delivery_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("supervisor_user_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("reject_reason", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_delivery_id"],
            ["project_deliveries.id"],
            name=op.f("fk_supervisor_reviews_project_delivery_id_project_deliveries"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_supervisor_reviews_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supervisor_reviews")),
    )
    op.create_index(
        op.f("ix_supervisor_reviews_project_delivery_id"), "supervisor_reviews", ["project_delivery_id"], unique=False
    )
    op.create_index(op.f("ix_supervisor_reviews_project_id"), "supervisor_reviews", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_supervisor_reviews_supervisor_user_id"), "supervisor_reviews", ["supervisor_user_id"], unique=False
    )
    op.create_table(
        "ticket_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("sender_user_id", sa.String(length=36), nullable=False),
        sa.Column("message_type", sa.String(length=20), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("is_internal", sa.Boolean(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attachment_file_asset_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], name=op.f("fk_ticket_messages_ticket_id_tickets")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_messages")),
    )
    op.create_index(op.f("ix_ticket_messages_sender_user_id"), "ticket_messages", ["sender_user_id"], unique=False)
    op.create_index(op.f("ix_ticket_messages_ticket_id"), "ticket_messages", ["ticket_id"], unique=False)
    op.create_table(
        "ticket_participants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("participant_role", sa.String(length=20), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], name=op.f("fk_ticket_participants_ticket_id_tickets")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_participants")),
    )
    op.create_index(op.f("ix_ticket_participants_ticket_id"), "ticket_participants", ["ticket_id"], unique=False)
    op.create_index(op.f("ix_ticket_participants_user_id"), "ticket_participants", ["user_id"], unique=False)
    op.create_table(
        "ratings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("customer_review_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("customer_user_id", sa.String(length=36), nullable=False),
        sa.Column("freelancer_profile_id", sa.String(length=36), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_review_id"], ["customer_reviews.id"], name=op.f("fk_ratings_customer_review_id_customer_reviews")
        ),
        sa.ForeignKeyConstraint(
            ["freelancer_profile_id"],
            ["freelancer_profiles.id"],
            name=op.f("fk_ratings_freelancer_profile_id_freelancer_profiles"),
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], name=op.f("fk_ratings_project_id_projects")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ratings")),
    )
    op.create_index(op.f("ix_ratings_customer_review_id"), "ratings", ["customer_review_id"], unique=False)
    op.create_index(op.f("ix_ratings_customer_user_id"), "ratings", ["customer_user_id"], unique=False)
    op.create_index(op.f("ix_ratings_freelancer_profile_id"), "ratings", ["freelancer_profile_id"], unique=False)
    op.create_index(op.f("ix_ratings_project_id"), "ratings", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ratings_project_id"), table_name="ratings")
    op.drop_index(op.f("ix_ratings_freelancer_profile_id"), table_name="ratings")
    op.drop_index(op.f("ix_ratings_customer_user_id"), table_name="ratings")
    op.drop_index(op.f("ix_ratings_customer_review_id"), table_name="ratings")
    op.drop_table("ratings")
    op.drop_index(op.f("ix_ticket_participants_user_id"), table_name="ticket_participants")
    op.drop_index(op.f("ix_ticket_participants_ticket_id"), table_name="ticket_participants")
    op.drop_table("ticket_participants")
    op.drop_index(op.f("ix_ticket_messages_ticket_id"), table_name="ticket_messages")
    op.drop_index(op.f("ix_ticket_messages_sender_user_id"), table_name="ticket_messages")
    op.drop_table("ticket_messages")
    op.drop_index(op.f("ix_supervisor_reviews_supervisor_user_id"), table_name="supervisor_reviews")
    op.drop_index(op.f("ix_supervisor_reviews_project_id"), table_name="supervisor_reviews")
    op.drop_index(op.f("ix_supervisor_reviews_project_delivery_id"), table_name="supervisor_reviews")
    op.drop_table("supervisor_reviews")
    op.drop_index(op.f("ix_project_revision_requests_project_id"), table_name="project_revision_requests")
    op.drop_index(op.f("ix_project_revision_requests_project_delivery_id"), table_name="project_revision_requests")
    op.drop_table("project_revision_requests")
    op.drop_index(op.f("ix_form_field_options_form_field_id"), table_name="form_field_options")
    op.drop_table("form_field_options")
    op.drop_index(op.f("ix_customer_reviews_project_id"), table_name="customer_reviews")
    op.drop_index(op.f("ix_customer_reviews_project_delivery_id"), table_name="customer_reviews")
    op.drop_index(op.f("ix_customer_reviews_customer_user_id"), table_name="customer_reviews")
    op.drop_table("customer_reviews")
    op.drop_index(op.f("ix_tickets_ticket_code"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_related_project_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_related_category_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_created_by_user_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_assigned_to_user_id"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_resumes_freelancer_profile_id"), table_name="resumes")
    op.drop_table("resumes")
    op.drop_index(op.f("ix_project_status_history_project_id"), table_name="project_status_history")
    op.drop_table("project_status_history")
    op.drop_index(op.f("ix_project_deliveries_project_id"), table_name="project_deliveries")
    op.drop_table("project_deliveries")
    op.drop_index(op.f("ix_project_applications_project_id"), table_name="project_applications")
    op.drop_index(op.f("ix_project_applications_freelancer_profile_id"), table_name="project_applications")
    op.drop_table("project_applications")
    op.drop_index(op.f("ix_portfolio_items_freelancer_profile_id"), table_name="portfolio_items")
    op.drop_table("portfolio_items")
    op.drop_index(op.f("ix_freelancer_level_history_new_level_id"), table_name="freelancer_level_history")
    op.drop_index(op.f("ix_freelancer_level_history_freelancer_profile_id"), table_name="freelancer_level_history")
    op.drop_table("freelancer_level_history")
    op.drop_index(op.f("ix_form_fields_form_template_id"), table_name="form_fields")
    op.drop_table("form_fields")
    op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_role_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_role_permissions_role_id"), table_name="role_permissions")
    op.drop_index(op.f("ix_role_permissions_permission_id"), table_name="role_permissions")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_jti"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_projects_project_code"), table_name="projects")
    op.drop_index(op.f("ix_projects_customer_user_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_category_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_assigned_supervisor_user_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_freelancer_profiles_user_id"), table_name="freelancer_profiles")
    op.drop_index(op.f("ix_freelancer_profiles_current_level_id"), table_name="freelancer_profiles")
    op.drop_table("freelancer_profiles")
    op.drop_index(op.f("ix_form_templates_template_key"), table_name="form_templates")
    op.drop_index(op.f("ix_form_templates_category_id"), table_name="form_templates")
    op.drop_table("form_templates")
    op.drop_index(op.f("ix_category_supervisors_supervisor_user_id"), table_name="category_supervisors")
    op.drop_index(op.f("ix_category_supervisors_category_id"), table_name="category_supervisors")
    op.drop_table("category_supervisors")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_roles_role_key"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_permission_key"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_freelancer_levels_level_key"), table_name="freelancer_levels")
    op.drop_table("freelancer_levels")
    op.drop_table("code_sequences")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_index(op.f("ix_categories_parent_category_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_category_key"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
