'use client';

import type { ReactNode } from 'react';
import { useRouter } from 'next/navigation';
import { useForm, type UseFormReturn } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { toast } from 'sonner';
import { Loader2, Plus, Save, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ActionDialog } from '@/components/ui/action-dialog';
import { FormFieldType } from '@/generated/api/models/formFieldType';
import type { CategoryResponse, FormFieldResponse } from '@/generated/api/models';
import { useCreateFormTemplate, useUpdateFormTemplate, usePublishFormTemplate, useDeleteFormTemplate, useAddField, useUpdateField, useRemoveField, useAddFieldOption, useUpdateFieldOption, useRemoveFieldOption } from '@/generated/api/form/form';

const fieldSchema = z.object({ field_key: z.string().min(1, 'کلید فیلد الزامی است'), label: z.string().min(1, 'عنوان فیلد الزامی است'), field_type: z.string().min(1), description: z.string().optional(), is_required: z.boolean(), is_repeatable: z.boolean(), is_unique: z.boolean() });
const optionSchema = z.object({ option_key: z.string().min(1, 'کلید گزینه الزامی است'), label: z.string().min(1, 'عنوان گزینه الزامی است'), value: z.string().min(1, 'مقدار گزینه الزامی است') });
const templateSchema = z.object({ category_id: z.string().min(1), name: z.string().min(1), template_key: z.string().min(1) });
const TYPE_LABELS: Record<string, string> = { text: 'متن کوتاه', textarea: 'متن بلند', number: 'عدد', decimal: 'عدد اعشاری', boolean: 'بله / خیر', date: 'تاریخ', datetime: 'تاریخ و زمان', email: 'ایمیل', phone: 'تلفن', url: 'لینک', select: 'انتخابی', multi_select: 'انتخاب چندگانه', file: 'فایل', json: 'JSON' };
const run = async (action: () => Promise<unknown>, success: string) => { try { await action(); toast.success(success); return true; } catch { toast.error('عملیات انجام نشد. دوباره تلاش کنید.'); return false; } };

export function CreateFormTemplateForm({ categories }: { categories: CategoryResponse[] }) { const router = useRouter(); const form = useForm<z.infer<typeof templateSchema>>({ resolver: zodResolver(templateSchema), defaultValues: { category_id: '', name: '', template_key: '' } }); const mutation = useCreateFormTemplate(); return <form onSubmit={form.handleSubmit(async (data) => { if (await run(() => mutation.mutateAsync({ data }), 'قالب ایجاد شد.')) { form.reset(); router.refresh(); } })} className="grid gap-4 rounded-xl border bg-card p-5 shadow-sm"><div><h2 className="font-semibold">ایجاد قالب جدید</h2><p className="mt-1 text-sm text-muted-foreground">اطلاعات پایه قالب فرم را وارد کنید.</p></div><div className="grid gap-4 sm:grid-cols-3"><Field label="دسته‌بندی"><Select value={form.watch('category_id')} onValueChange={(v) => form.setValue('category_id', v, { shouldValidate: true })}><SelectTrigger className="w-full"><SelectValue placeholder="دسته‌بندی را انتخاب کنید" /></SelectTrigger><SelectContent>{categories.map((c) => <SelectItem key={c.category_id} value={c.category_id}>{c.name}</SelectItem>)}</SelectContent></Select></Field><Field label="نام قالب"><Input placeholder="مثلاً اطلاعات پروژه" {...form.register('name')} /></Field><Field label="کلید یکتا"><Input dir="ltr" placeholder="project_details" {...form.register('template_key')} /></Field></div><Button type="submit" disabled={mutation.isPending}>{mutation.isPending ? <Loader2 className="animate-spin" /> : <Plus />}ایجاد قالب</Button></form>; }

export function EditFormTemplateForm({ templateId, name, enabled }: { templateId: string; name: string; enabled: boolean }) { const router = useRouter(); const form = useForm({ resolver: zodResolver(z.object({ name: z.string().min(1) })), defaultValues: { name } }); const mutation = useUpdateFormTemplate(); if (!enabled) return null; return <form onSubmit={form.handleSubmit(async (data) => { if (await run(() => mutation.mutateAsync({ templateId, data }), 'نام قالب ذخیره شد.')) router.refresh(); })} className="flex flex-wrap items-end gap-3"><Field label="نام قالب" className="min-w-56 flex-1"><Input {...form.register('name')} placeholder="نام قالب" /></Field><Button type="submit" disabled={mutation.isPending}><Save />ذخیره</Button></form>; }

export function TemplateActions({ templateId, status }: { templateId: string; status: string }) { const router = useRouter(); const publish = usePublishFormTemplate(); const remove = useDeleteFormTemplate(); return <div className="flex flex-wrap gap-2">{status === 'draft' ? <Button onClick={() => void run(async () => { await publish.mutateAsync({ templateId }); router.refresh(); }, 'قالب منتشر شد.')} disabled={publish.isPending}><Save />انتشار قالب</Button> : <Badge variant="secondary">{status === 'published' ? 'منتشر شده' : 'بایگانی شده'}</Badge>}<ActionDialog trigger={<Button variant="destructive"><Trash2 />حذف قالب</Button>} title="حذف قالب" description="این عملیات قابل بازگشت نیست." confirmLabel="حذف قالب" destructive onConfirm={() => remove.mutateAsync({ templateId })} onDone={() => { toast.success('قالب حذف شد.'); router.push('/admin/form-templates'); }} /></div>; }

export function AddFieldForm({ templateId, enabled }: { templateId: string; enabled: boolean }) { const router = useRouter(); const form = useForm<z.infer<typeof fieldSchema>>({ resolver: zodResolver(fieldSchema), defaultValues: { field_key: '', label: '', field_type: FormFieldType.text, description: '', is_required: false, is_repeatable: false, is_unique: false } }); const mutation = useAddField(); if (!enabled) return <ReadOnlyNotice />; return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="size-5 text-primary" />افزودن فیلد</CardTitle></CardHeader><CardContent><form onSubmit={form.handleSubmit(async (data) => { const ok = await run(() => mutation.mutateAsync({ templateId, data: { ...data, field_type: data.field_type as FormFieldType, description: data.description || null } }), 'فیلد اضافه شد.'); if (ok) { form.reset(); router.refresh(); } })} className="grid gap-4"><div className="grid gap-4 sm:grid-cols-3"><Field label="کلید فیلد"><Input dir="ltr" placeholder="project_title" {...form.register('field_key')} /></Field><Field label="عنوان نمایشی"><Input placeholder="عنوان پروژه" {...form.register('label')} /></Field><Field label="نوع فیلد"><Select value={form.watch('field_type')} onValueChange={(v) => form.setValue('field_type', v, { shouldValidate: true })}><SelectTrigger className="w-full"><SelectValue placeholder="نوع فیلد را انتخاب کنید" /></SelectTrigger><SelectContent>{Object.values(FormFieldType).map((v) => <SelectItem key={v} value={v}>{TYPE_LABELS[v] ?? v}</SelectItem>)}</SelectContent></Select></Field></div><Field label="توضیحات"><Textarea placeholder="راهنمای کوتاه برای کاربر (اختیاری)" {...form.register('description')} /></Field><Flags form={form} /><Button type="submit" disabled={mutation.isPending}>{mutation.isPending ? <Loader2 className="animate-spin" /> : <Plus />}افزودن فیلد</Button></form></CardContent></Card>; }

function FieldEditor({ templateId, field }: { templateId: string; field: FormFieldResponse }) { const router = useRouter(); const form = useForm<z.infer<typeof fieldSchema>>({ resolver: zodResolver(fieldSchema), defaultValues: { field_key: field.field_key, label: field.label, field_type: field.field_type, description: field.description ?? '', is_required: field.is_required, is_repeatable: field.is_repeatable, is_unique: field.is_unique } }); const mutation = useUpdateField(); return <form onSubmit={form.handleSubmit(async (data) => { if (await run(() => mutation.mutateAsync({ templateId, fieldId: field.field_id, data: { label: data.label, field_type: data.field_type as FormFieldType, description: data.description || null, is_required: data.is_required, is_repeatable: data.is_repeatable, is_unique: data.is_unique } }), 'فیلد ویرایش شد.')) router.refresh(); })} className="grid gap-4 rounded-lg bg-muted/40 p-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="کلید فیلد"><Input dir="ltr" value={field.field_key} disabled /></Field><Field label="عنوان نمایشی"><Input placeholder="عنوان فیلد" {...form.register('label')} /></Field></div><Field label="توضیحات"><Textarea placeholder="راهنمای کوتاه برای کاربر" {...form.register('description')} /></Field><Flags form={form} /><Button type="submit" size="sm" disabled={mutation.isPending}>{mutation.isPending ? <Loader2 className="animate-spin" /> : <Save />}ذخیره تغییرات</Button></form>; }

export function FieldActions({ templateId, fieldId, enabled, field }: { templateId: string; fieldId: string; enabled: boolean; field?: FormFieldResponse }) { const router = useRouter(); const remove = useRemoveField(); if (!enabled) return null; return <div className="grid gap-3">{field ? <FieldEditor templateId={templateId} field={field} /> : null}<div className="flex justify-end"><ActionDialog trigger={<Button size="sm" variant="ghost"><Trash2 />حذف فیلد</Button>} title="حذف فیلد" description="گزینه‌های این فیلد نیز حذف خواهند شد." confirmLabel="حذف فیلد" destructive onConfirm={() => remove.mutateAsync({ templateId, fieldId })} onDone={() => { toast.success('فیلد حذف شد.'); router.refresh(); }} /></div></div>; }

export function AddOptionForm({ templateId, fieldId, enabled }: { templateId: string; fieldId: string; enabled: boolean }) { const router = useRouter(); const form = useForm<z.infer<typeof optionSchema>>({ resolver: zodResolver(optionSchema), defaultValues: { option_key: '', label: '', value: '' } }); const mutation = useAddFieldOption(); if (!enabled) return null; return <form onSubmit={form.handleSubmit(async (data) => { if (await run(() => mutation.mutateAsync({ templateId, fieldId, data }), 'گزینه اضافه شد.')) { form.reset(); router.refresh(); } })} className="grid gap-3 rounded-lg border border-dashed p-4"><p className="text-sm font-medium">افزودن گزینه</p><div className="grid gap-3 sm:grid-cols-3"><Field label="کلید گزینه"><Input dir="ltr" placeholder="beginner" {...form.register('option_key')} /></Field><Field label="عنوان"><Input placeholder="مبتدی" {...form.register('label')} /></Field><Field label="مقدار"><Input placeholder="beginner" {...form.register('value')} /></Field></div><Button type="submit" size="sm" disabled={mutation.isPending}><Plus />افزودن گزینه</Button></form>; }

export function OptionActions({ templateId, fieldId, optionId, enabled, option }: { templateId: string; fieldId: string; optionId: string; enabled: boolean; option?: { option_key: string; label: string; value: string } }) { const router = useRouter(); const form = useForm({ defaultValues: { label: option?.label ?? '', value: option?.value ?? '' } }); const update = useUpdateFieldOption(); const remove = useRemoveFieldOption(); if (!enabled) return null; return <div className="mt-2 flex flex-wrap items-end gap-2"><Field label="عنوان"><Input placeholder="عنوان گزینه" {...form.register('label')} /></Field><Field label="مقدار"><Input placeholder="مقدار گزینه" {...form.register('value')} /></Field><Button size="sm" variant="outline" onClick={() => void form.handleSubmit(async (data) => { if (await run(() => update.mutateAsync({ templateId, fieldId, optionId, data }), 'گزینه ویرایش شد.')) router.refresh(); })()} disabled={update.isPending}><Save /></Button><ActionDialog trigger={<Button size="sm" variant="ghost"><Trash2 /></Button>} title="حذف گزینه" confirmLabel="حذف گزینه" destructive onConfirm={() => remove.mutateAsync({ templateId, fieldId, optionId })} onDone={() => { toast.success('گزینه حذف شد.'); router.refresh(); }} /></div>; }

function Flags({ form }: { form: UseFormReturn<z.infer<typeof fieldSchema>> }) { return <div className="flex flex-wrap gap-4">{[['is_required', 'الزامی'], ['is_repeatable', 'تکرارشونده'], ['is_unique', 'مقدار یکتا']].map(([name, label]) => <label key={name} className="inline-flex min-h-11 items-center gap-2 text-sm"><Checkbox checked={Boolean(form.watch(name as keyof z.infer<typeof fieldSchema>))} onCheckedChange={(v) => form.setValue(name as keyof z.infer<typeof fieldSchema>, v === true)} /><span>{label}</span></label>)}</div>; }
function Field({ label, children, className = '' }: { label: string; children: ReactNode; className?: string }) { return <div className={`grid gap-1.5 ${className}`}><Label>{label}</Label>{children}</div>; }
function ReadOnlyNotice() { return <div className="rounded-xl border border-dashed bg-muted/30 p-5 text-sm text-muted-foreground">این قالب منتشر شده است و در حال حاضر فقط خواندنی است.</div>; }
