PERMISSION_FREELANCER_CREATE_OWN = "freelancer.create_own"
PERMISSION_FREELANCER_CREATE_ON_BEHALF = "freelancer.create_on_behalf"
PERMISSION_FREELANCER_APPROVE = "freelancer.approve"
PERMISSION_FREELANCER_ASSIGN_LEVEL = "freelancer.assign_level"
PERMISSION_FREELANCER_READ_OWN = "freelancer.read_own"
PERMISSION_FREELANCER_READ_ANY = "freelancer.read_any"
PERMISSION_FREELANCER_DELETE_ANY = "freelancer.delete_any"
